# docker-compose.yml

version: '3.8'

services:
  web:
    build: .
    command: bash -c 'while !</dev/tcp/db/5432; do sleep 1; done; uvicorn main:app --host 0.0.0.0'
    volumes:
      - ./app:/app
    ports:
      - 8008:8000
    environment:
      - DATABASE_URL=postgresql://green:green@db:5432/green_db
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    expose:
      - 5432
    environment:
      - POSTGRES_USER=green
      - POSTGRES_PASSWORD=green
      - POSTGRES_DB=green_db
  minio:
    image: minio/minio
    command: server --console-address ":9001" /data/
    container_name: green_minio
    environment:
      - MINIO_ROOT_USER=greenminio
      - MINIO_ROOT_PASSWORD=minio123
    ports:
     - "9000:9000"
     - "9001:9001"
    volumes:
     - minio-storage:/data
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3

volumes:
  postgres_data:
  minio-storage: